# This workflow defines the go and ui related jobs.
#
# First, we use [dorny/paths-filter@v2](https://github.com/dorny/paths-filter) to
# detect changes in go and ui related files, and then run the corresponding sub-jobs
# based on the changes.
#
# Please note that due to the GitHub required checks, the `go` and `ui` jobs are
# also need to run to report the status. So here we need to define an additional
# "skip" file to ensure that the status is reported. For details, please refer to:
#
# - `ci_skip.yml`
# - https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: ci

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go:
              - Makefile
              - go.*
              - '**.go'
              - 'helm/**'
  go:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - verify
          - build
          - test
    steps:
      - uses: actions/checkout@v2

      - name: Build Waterline Build Env
        env:
          IMAGE_BUILD_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-build-env-image') }}
        run: |
          if [ "${IMAGE_BUILD_ENV_BUILD}" = "true" ] ; then
            export IMAGE_BUILD_ENV_BUILD=1;
          else
            export IMAGE_BUILD_ENV_BUILD=0;
          fi

          make image-build-env

      - name: Build Waterline Dev Env
        env:
          IMAGE_DEV_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-dev-env-image') }}
        run: |
          if [ "${IMAGE_DEV_ENV_BUILD}" = "true" ] ; then
            export IMAGE_DEV_ENV_BUILD=1;
          else
            export IMAGE_DEV_ENV_BUILD=0;
          fi

          make image-dev-env

      - name: ${{ matrix.job }}
        env:
          job: ${{ matrix.job }}
        run: |
          if [[ "$job" == "verify" ]]; then
            make check
            echo "Please make check before creating a PR"
            git diff --quiet -- . || (git diff | cat && false)
          elif [[ "$job" == "build" ]]; then
            make image
          elif [[ "$job" == "test" ]]; then
            ROOT=$(pwd)
            KUBEBUILDER_ASSETS=${ROOT}/output/bin/kubebuilder/bin make test
          else
            make $job
          fi
