# Please refer to the file comments in `ci.yml` for more information.
name: ci

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  skip-changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go:
              - Makefile
              - go.*
              - '**.go'
              - 'helm/**'
  go:
    needs: skip-changes
    if: ${{ needs.skip-changes.outputs.go != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - verify
          - build
          - test
    steps:
      - run: echo "Not required"
