name: Unit Test And Code Coverage

# this workflow would work on all the prs
on:
  pull_request:
    paths:
      - Makefile
      - go.*
      - "**.go"
  push:
    paths:
      - Makefile
      - go.*
      - "**.go"

jobs:
  unitTestAndCodeCoverage:
    name: "Unit Test And Code Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Waterline Build Env
        if: ${{ github.event.pull_request }}
        env:
          IMAGE_BUILD_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-build-env-image') }}
        run: |
          if [ "${IMAGE_BUILD_ENV_BUILD}" = "true" ] ; then
            export IMAGE_BUILD_ENV_BUILD=1; 
          else 
            export IMAGE_BUILD_ENV_BUILD=0; 
          fi

          make image-build-env
      
      - name: Build Waterline Dev Env
        if: ${{ github.event.pull_request }}
        env:
          IMAGE_DEV_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-dev-env-image') }}
        run: |
          if [ "${IMAGE_DEV_ENV_BUILD}" = "true" ] ; then
            export IMAGE_DEV_ENV_BUILD=1; 
          else 
            export IMAGE_DEV_ENV_BUILD=0; 
          fi

          make image-dev-env

      - name: Unit Test
        run: |
          make test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./cover.out
          verbose: true
          fail_ci_if_error: true
