name: Test install.sh
on:
  pull_request:
    branches:
      - master
    paths:
      - 'install.sh'

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-script-test') }}
    steps:
      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - name: Creating kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install Chaos Mesh
        run: |
          bash install.sh --runtime containerd --crd ./manifests/crd.yaml

      - name: Run integration test
        run: |
          bash test/integration_test/run.sh
