name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 21 days'
        stale-pr-message: 'This pr is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 21 days'
        days-before-stale: 90
        days-before-close: 21
        stale-issue-label: 'lifecycle/stale'
        stale-pr-label: 'lifecycle/stale'
        exempt-issue-labels: 'lifecycle/frozen,type/enhancement,type/suggestion,type/bug'
        exempt-pr-labels: 'lifecycle/frozen,type/enhancement,type/bug-fix'
